#!/usr/bin/env php
<?php

/*

Change the library location according to the lib folder location

*/

require_once('./lib/Suruh_lib.php');

require_once('./bin/Pattern.php');

(new suruh)->action($argv);

?>