#!/usr/bin/env php
<?php

/*

Please change the library location according to the lib folder location


- suruh
- /lib/suruh_lib.php
- /bin/Pattern.php

*/

require_once('./lib/suruh_lib.php');

(new suruh)->action($argv);

?>